spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.2/ghes-3.2.yaml
namespace:
  source: ApiClients\Client\GitHubEnterprise
  test: ApiClients\Tests\Client\GitHubEnterprise
destination:
  root: ../
  source: src
  test: tests
templates:
  dir: ../templates
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
contentType:
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Json
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Raw
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
