spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.3/ghes-3.3.yaml
namespace: ApiClients\Client\GitHubEnterprise
destination: ../src
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
