<?php

declare(strict_types=1);

namespace ApiClients\Client\GitHubEnterprise\Schema;

use ApiClients\Client\GitHubEnterprise\Schema;
use EventSauce\ObjectHydrator\MapFrom;

final readonly class Feed
{
    public const SCHEMA_JSON         = '{"title":"Feed","required":["_links","timeline_url","user_url"],"type":"object","properties":{"timeline_url":{"type":"string","examples":["https:\\/\\/github.com\\/timeline"]},"user_url":{"type":"string","examples":["https:\\/\\/github.com\\/{user}"]},"current_user_public_url":{"type":"string","examples":["https:\\/\\/github.com\\/octocat"]},"current_user_url":{"type":"string","examples":["https:\\/\\/github.com\\/octocat.private?token=abc123"]},"current_user_actor_url":{"type":"string","examples":["https:\\/\\/github.com\\/octocat.private.actor?token=abc123"]},"current_user_organization_url":{"type":"string","examples":["https:\\/\\/github.com\\/octocat-org"]},"current_user_organization_urls":{"type":"array","items":{"type":"string","format":"uri"},"examples":["https:\\/\\/github.com\\/organizations\\/github\\/octocat.private.atom?token=abc123"]},"_links":{"required":["timeline","user"],"type":"object","properties":{"timeline":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"user":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"security_advisories":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"current_user":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"current_user_public":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"current_user_actor":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"current_user_organization":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"},"current_user_organizations":{"type":"array","items":{"title":"Link With Type","required":["href","type"],"type":"object","properties":{"href":{"type":"string"},"type":{"type":"string"}},"description":"Hypermedia Link with Type"}}}}},"description":"Feed"}';
    public const SCHEMA_TITLE        = 'Feed';
    public const SCHEMA_DESCRIPTION  = 'Feed';
    public const SCHEMA_EXAMPLE_DATA = '{"timeline_url":"https:\\/\\/github.com\\/timeline","user_url":"https:\\/\\/github.com\\/{user}","current_user_public_url":"https:\\/\\/github.com\\/octocat","current_user_url":"https:\\/\\/github.com\\/octocat.private?token=abc123","current_user_actor_url":"https:\\/\\/github.com\\/octocat.private.actor?token=abc123","current_user_organization_url":"https:\\/\\/github.com\\/octocat-org","current_user_organization_urls":["https:\\/\\/github.com\\/organizations\\/github\\/octocat.private.atom?token=abc123"],"_links":{"timeline":{"href":"generated_href_null","type":"generated_type_null"},"user":{"href":"generated_href_null","type":"generated_type_null"},"security_advisories":{"href":"generated_href_null","type":"generated_type_null"},"current_user":{"href":"generated_href_null","type":"generated_type_null"},"current_user_public":{"href":"generated_href_null","type":"generated_type_null"},"current_user_actor":{"href":"generated_href_null","type":"generated_type_null"},"current_user_organization":{"href":"generated_href_null","type":"generated_type_null"},"current_user_organizations":[{"href":"generated_href_null","type":"generated_type_null"}]}}';

    /**
     * @param ?array<string> $currentUserOrganizationUrls
     */
    public function __construct(#[MapFrom('timeline_url')] public string $timelineUrl, #[MapFrom('user_url')] public string $userUrl, #[MapFrom('current_user_public_url')] public ?string $currentUserPublicUrl, #[MapFrom('current_user_url')] public ?string $currentUserUrl, #[MapFrom('current_user_actor_url')] public ?string $currentUserActorUrl, #[MapFrom('current_user_organization_url')] public ?string $currentUserOrganizationUrl, #[MapFrom('current_user_organization_urls')] public ?array $currentUserOrganizationUrls, #[MapFrom('_links')] public Schema\Feed\Links $links)
    {
    }
}
