spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.6/ghes-3.6.yaml
namespace: ApiClients\Client\GitHubEnterprise
destination: ../src
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
