spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghec/ghec.yaml
namespace: ApiClients\Client\GitHubEnterpriseCloud
destination: ../src
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
