state:
  file: etc/openapi-client-generator.state
  additionalFiles:
    - composer.json
    - composer.lock
    - ../../composer.json
    - ../../composer.lock
spec: ../../../etc/specs/GitHubEnterpriseCloud/current.spec.yaml
namespace:
  source: ApiClients\Client\GitHubEnterpriseCloud
  test: ApiClients\Tests\Client\GitHubEnterpriseCloud
entryPoints:
  call: true
  operations: true
  webHooks: true
destination:
  root: ../
  source: src
  test: tests
templates:
  dir: ../templates
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
contentType:
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Json
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Raw
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
