spec: {{ specUrl }}
namespace: ApiClients\Client\{{ namespace }}
destination: ../src
schemas:
  allowDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
