spec: {{ specUrl }}
namespace:
  source: ApiClients\Client\{{ namespace }}
  test: ApiClients\Tests\Client\{{ namespace }}
destination:
  root: ../
  source: src
  test: tests
templates:
  dir: ../templates
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
