spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.5/ghes-3.5.yaml
namespace: ApiClients\Client\GitHubEnterprise
destination: ../src
voter:
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
