<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHub\Contract;

/**
 * @property int $id
 * @property string $nodeId
 * @property string $name
 * @property string $fullName
 * @property \ApiClients\Client\GitHub\Schema\SimpleUser $owner
 * @property bool $private
 * @property string $htmlUrl
 * @property ?string $description
 * @property bool $fork
 * @property string $url
 * @property string $archiveUrl
 * @property string $assigneesUrl
 * @property string $blobsUrl
 * @property string $branchesUrl
 * @property string $collaboratorsUrl
 * @property string $commentsUrl
 * @property string $commitsUrl
 * @property string $compareUrl
 * @property string $contentsUrl
 * @property string $contributorsUrl
 * @property string $deploymentsUrl
 * @property string $downloadsUrl
 * @property string $eventsUrl
 * @property string $forksUrl
 * @property string $gitCommitsUrl
 * @property string $gitRefsUrl
 * @property string $gitTagsUrl
 * @property string $gitUrl
 * @property string $issueCommentUrl
 * @property string $issueEventsUrl
 * @property string $issuesUrl
 * @property string $keysUrl
 * @property string $labelsUrl
 * @property string $languagesUrl
 * @property string $mergesUrl
 * @property string $milestonesUrl
 * @property string $notificationsUrl
 * @property string $pullsUrl
 * @property string $releasesUrl
 * @property string $sshUrl
 * @property string $stargazersUrl
 * @property string $statusesUrl
 * @property string $subscribersUrl
 * @property string $subscriptionUrl
 * @property string $tagsUrl
 * @property string $teamsUrl
 * @property string $treesUrl
 * @property string $cloneUrl
 * @property ?string $mirrorUrl
 * @property string $hooksUrl
 * @property string $svnUrl
 * @property ?string $homepage
 * @property ?string $language
 * @property int $forksCount
 * @property int $stargazersCount
 * @property int $watchersCount
 * @property int $size
 * @property string $defaultBranch
 * @property int $openIssuesCount
 * @property ?bool $isTemplate
 * @property ?array $topics
 * @property bool $hasIssues
 * @property bool $hasProjects
 * @property bool $hasWiki
 * @property bool $hasPages
 * @property ?bool $hasDownloads
 * @property bool $hasDiscussions
 * @property bool $archived
 * @property bool $disabled
 * @property ?string $visibility
 * @property string $pushedAt
 * @property string $createdAt
 * @property string $updatedAt
 * @property ?\ApiClients\Client\GitHub\Schema\FullRepository\Permissions $permissions
 * @property ?bool $allowRebaseMerge
 * @property ?\ApiClients\Client\GitHub\Schema\Repository $templateRepository
 * @property ?string $tempCloneToken
 * @property ?bool $allowSquashMerge
 * @property ?bool $allowAutoMerge
 * @property ?bool $deleteBranchOnMerge
 * @property ?bool $allowMergeCommit
 * @property ?bool $allowUpdateBranch
 * @property ?bool $useSquashPrTitleAsDefault
 * @property ?string $squashMergeCommitTitle
 * @property ?string $squashMergeCommitMessage
 * @property ?string $mergeCommitTitle
 * @property ?string $mergeCommitMessage
 * @property ?bool $allowForking
 * @property ?bool $webCommitSignoffRequired
 * @property int $subscribersCount
 * @property int $networkCount
 * @property ?\ApiClients\Client\GitHub\Schema\LicenseSimple $license
 * @property ?\ApiClients\Client\GitHub\Schema\SimpleUser $organization
 * @property ?\ApiClients\Client\GitHub\Schema\Repository $parent
 * @property ?\ApiClients\Client\GitHub\Schema\Repository $source
 * @property int $forks
 * @property ?string $masterBranch
 * @property int $openIssues
 * @property int $watchers
 * @property ?bool $anonymousAccessEnabled
 * @property ?\ApiClients\Client\GitHub\Schema\CodeOfConductSimple $codeOfConduct
 * @property ?\ApiClients\Client\GitHub\Schema\SecurityAndAnalysis $securityAndAnalysis
 * @property ?\ApiClients\Client\GitHub\Schema\FullRepository\CustomProperties $customProperties
 */
interface FullRepository
{
}
