<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHubEnterprise\Schema\WebhookPullRequestConvertedToDraft\PullRequest\Head;

use ApiClients\Client\GitHubEnterprise\Hydrator;
use ApiClients\Client\GitHubEnterprise\Operation;
use ApiClients\Client\GitHubEnterprise\Schema;
use ApiClients\Client\GitHubEnterprise\WebHook;
final readonly class Repo
{
    public const SCHEMA_JSON = '{"type":["object","null"],"properties":{"allow_auto_merge":{"type":"boolean"},"allow_forking":{"type":"boolean"},"allow_merge_commit":{"type":"boolean"},"allow_rebase_merge":{"type":"boolean"},"allow_squash_merge":{"type":"boolean"},"allow_update_branch":{"type":"boolean"},"archive_url":{"type":"string"},"archived":{"type":"boolean"},"assignees_url":{"type":"string"},"blobs_url":{"type":"string"},"branches_url":{"type":"string"},"clone_url":{"type":"string"},"collaborators_url":{"type":"string"},"comments_url":{"type":"string"},"commits_url":{"type":"string"},"compare_url":{"type":"string"},"contents_url":{"type":"string"},"contributors_url":{"type":"string"},"created_at":{"type":"string"},"default_branch":{"type":"string"},"delete_branch_on_merge":{"type":"boolean"},"deployments_url":{"type":"string"},"description":{"type":["string","null"]},"disabled":{"type":"boolean"},"downloads_url":{"type":"string"},"events_url":{"type":"string"},"fork":{"type":"boolean"},"forks":{"type":"integer"},"forks_count":{"type":"integer"},"forks_url":{"type":"string"},"full_name":{"type":"string"},"git_commits_url":{"type":"string"},"git_refs_url":{"type":"string"},"git_tags_url":{"type":"string"},"git_url":{"type":"string"},"has_downloads":{"type":"boolean"},"has_issues":{"type":"boolean"},"has_pages":{"type":"boolean"},"has_projects":{"type":"boolean"},"has_wiki":{"type":"boolean"},"homepage":{"type":["string","null"]},"hooks_url":{"type":"string"},"html_url":{"type":"string"},"id":{"type":"integer"},"is_template":{"type":"boolean"},"issue_comment_url":{"type":"string"},"issue_events_url":{"type":"string"},"issues_url":{"type":"string"},"keys_url":{"type":"string"},"labels_url":{"type":"string"},"language":{"type":["string","null"]},"languages_url":{"type":"string"},"license":{"type":["object","null"]},"merge_commit_message":{"enum":["PR_BODY","PR_TITLE","BLANK"],"type":"string"},"merge_commit_title":{"enum":["PR_TITLE","MERGE_MESSAGE"],"type":"string"},"merges_url":{"type":"string"},"milestones_url":{"type":"string"},"mirror_url":{"type":["null"]},"name":{"type":"string"},"node_id":{"type":"string"},"notifications_url":{"type":"string"},"open_issues":{"type":"integer"},"open_issues_count":{"type":"integer"},"owner":{"type":"object","properties":{"avatar_url":{"type":"string"},"events_url":{"type":"string"},"followers_url":{"type":"string"},"following_url":{"type":"string"},"gists_url":{"type":"string"},"gravatar_id":{"type":"string"},"html_url":{"type":"string"},"id":{"type":"integer"},"login":{"type":"string"},"node_id":{"type":"string"},"organizations_url":{"type":"string"},"received_events_url":{"type":"string"},"repos_url":{"type":"string"},"site_admin":{"type":"boolean"},"starred_url":{"type":"string"},"subscriptions_url":{"type":"string"},"type":{"type":"string"},"url":{"type":"string"}}},"private":{"type":"boolean"},"pulls_url":{"type":"string"},"pushed_at":{"type":"string"},"releases_url":{"type":"string"},"size":{"type":"integer"},"squash_merge_commit_message":{"enum":["PR_BODY","COMMIT_MESSAGES","BLANK"],"type":"string"},"squash_merge_commit_title":{"enum":["PR_TITLE","COMMIT_OR_PR_TITLE"],"type":"string"},"ssh_url":{"type":"string"},"stargazers_count":{"type":"integer"},"stargazers_url":{"type":"string"},"statuses_url":{"type":"string"},"subscribers_url":{"type":"string"},"subscription_url":{"type":"string"},"svn_url":{"type":"string"},"tags_url":{"type":"string"},"teams_url":{"type":"string"},"topics":{"type":"array","items":{"type":["string","null"]}},"trees_url":{"type":"string"},"updated_at":{"type":"string"},"url":{"type":"string"},"use_squash_pr_title_as_default":{"type":"boolean"},"visibility":{"type":"string"},"watchers":{"type":"integer"},"watchers_count":{"type":"integer"},"web_commit_signoff_required":{"type":"boolean"}}}';
    public const SCHEMA_TITLE = '';
    public const SCHEMA_DESCRIPTION = '';
    public const SCHEMA_EXAMPLE_DATA = '{"allow_auto_merge":false,"allow_forking":false,"allow_merge_commit":false,"allow_rebase_merge":false,"allow_squash_merge":false,"allow_update_branch":false,"archive_url":"generated_archive_url","archived":false,"assignees_url":"generated_assignees_url","blobs_url":"generated_blobs_url","branches_url":"generated_branches_url","clone_url":"generated_clone_url","collaborators_url":"generated_collaborators_url","comments_url":"generated_comments_url","commits_url":"generated_commits_url","compare_url":"generated_compare_url","contents_url":"generated_contents_url","contributors_url":"generated_contributors_url","created_at":"generated_created_at","default_branch":"generated_default_branch","delete_branch_on_merge":false,"deployments_url":"generated_deployments_url","description":"generated_description","disabled":false,"downloads_url":"generated_downloads_url","events_url":"generated_events_url","fork":false,"forks":13,"forks_count":13,"forks_url":"generated_forks_url","full_name":"generated_full_name","git_commits_url":"generated_git_commits_url","git_refs_url":"generated_git_refs_url","git_tags_url":"generated_git_tags_url","git_url":"generated_git_url","has_downloads":false,"has_issues":false,"has_pages":false,"has_projects":false,"has_wiki":false,"homepage":"generated_homepage","hooks_url":"generated_hooks_url","html_url":"generated_html_url","id":13,"is_template":false,"issue_comment_url":"generated_issue_comment_url","issue_events_url":"generated_issue_events_url","issues_url":"generated_issues_url","keys_url":"generated_keys_url","labels_url":"generated_labels_url","language":"generated_language","languages_url":"generated_languages_url","license":[],"merge_commit_message":"generated_merge_commit_message","merge_commit_title":"generated_merge_commit_title","merges_url":"generated_merges_url","milestones_url":"generated_milestones_url","mirror_url":"generated_mirror_url","name":"generated_name","node_id":"generated_node_id","notifications_url":"generated_notifications_url","open_issues":13,"open_issues_count":13,"owner":{"avatar_url":"generated_avatar_url","events_url":"generated_events_url","followers_url":"generated_followers_url","following_url":"generated_following_url","gists_url":"generated_gists_url","gravatar_id":"generated_gravatar_id","html_url":"generated_html_url","id":13,"login":"generated_login","node_id":"generated_node_id","organizations_url":"generated_organizations_url","received_events_url":"generated_received_events_url","repos_url":"generated_repos_url","site_admin":false,"starred_url":"generated_starred_url","subscriptions_url":"generated_subscriptions_url","type":"generated_type","url":"generated_url"},"private":false,"pulls_url":"generated_pulls_url","pushed_at":"generated_pushed_at","releases_url":"generated_releases_url","size":13,"squash_merge_commit_message":"generated_squash_merge_commit_message","squash_merge_commit_title":"generated_squash_merge_commit_title","ssh_url":"generated_ssh_url","stargazers_count":13,"stargazers_url":"generated_stargazers_url","statuses_url":"generated_statuses_url","subscribers_url":"generated_subscribers_url","subscription_url":"generated_subscription_url","svn_url":"generated_svn_url","tags_url":"generated_tags_url","teams_url":"generated_teams_url","topics":[null],"trees_url":"generated_trees_url","updated_at":"generated_updated_at","url":"generated_url","use_squash_pr_title_as_default":false,"visibility":"generated_visibility","watchers":13,"watchers_count":13,"web_commit_signoff_required":false}';
    public ?bool $allow_auto_merge;
    public ?bool $allow_forking;
    public ?bool $allow_merge_commit;
    public ?bool $allow_rebase_merge;
    public ?bool $allow_squash_merge;
    public ?bool $allow_update_branch;
    public ?string $archive_url;
    public ?bool $archived;
    public ?string $assignees_url;
    public ?string $blobs_url;
    public ?string $branches_url;
    public ?string $clone_url;
    public ?string $collaborators_url;
    public ?string $comments_url;
    public ?string $commits_url;
    public ?string $compare_url;
    public ?string $contents_url;
    public ?string $contributors_url;
    public ?string $created_at;
    public ?string $default_branch;
    public ?bool $delete_branch_on_merge;
    public ?string $deployments_url;
    public ?string $description;
    public ?bool $disabled;
    public ?string $downloads_url;
    public ?string $events_url;
    public ?bool $fork;
    public ?int $forks;
    public ?int $forks_count;
    public ?string $forks_url;
    public ?string $full_name;
    public ?string $git_commits_url;
    public ?string $git_refs_url;
    public ?string $git_tags_url;
    public ?string $git_url;
    public ?bool $has_downloads;
    public ?bool $has_issues;
    public ?bool $has_pages;
    public ?bool $has_projects;
    public ?bool $has_wiki;
    public ?string $homepage;
    public ?string $hooks_url;
    public ?string $html_url;
    public ?int $id;
    public ?bool $is_template;
    public ?string $issue_comment_url;
    public ?string $issue_events_url;
    public ?string $issues_url;
    public ?string $keys_url;
    public ?string $labels_url;
    public ?string $language;
    public ?string $languages_url;
    public ?Schema\WebhookCheckSuiteCompleted\ActionsMeta $license;
    public ?string $merge_commit_message;
    public ?string $merge_commit_title;
    public ?string $merges_url;
    public ?string $milestones_url;
    public mixed $mirror_url;
    public ?string $name;
    public ?string $node_id;
    public ?string $notifications_url;
    public ?int $open_issues;
    public ?int $open_issues_count;
    public ?Schema\WebhookDeploymentCreated\WorkflowRun\HeadRepository\Owner $owner;
    public ?bool $private;
    public ?string $pulls_url;
    public ?string $pushed_at;
    public ?string $releases_url;
    public ?int $size;
    public ?string $squash_merge_commit_message;
    public ?string $squash_merge_commit_title;
    public ?string $ssh_url;
    public ?int $stargazers_count;
    public ?string $stargazers_url;
    public ?string $statuses_url;
    public ?string $subscribers_url;
    public ?string $subscription_url;
    public ?string $svn_url;
    public ?string $tags_url;
    public ?string $teams_url;
    /**
     * @var array<string>
     */
    public ?array $topics;
    public ?string $trees_url;
    public ?string $updated_at;
    public ?string $url;
    public ?bool $use_squash_pr_title_as_default;
    public ?string $visibility;
    public ?int $watchers;
    public ?int $watchers_count;
    public ?bool $web_commit_signoff_required;
    public function __construct(bool $allow_auto_merge, bool $allow_forking, bool $allow_merge_commit, bool $allow_rebase_merge, bool $allow_squash_merge, bool $allow_update_branch, string $archive_url, bool $archived, string $assignees_url, string $blobs_url, string $branches_url, string $clone_url, string $collaborators_url, string $comments_url, string $commits_url, string $compare_url, string $contents_url, string $contributors_url, string $created_at, string $default_branch, bool $delete_branch_on_merge, string $deployments_url, string $description, bool $disabled, string $downloads_url, string $events_url, bool $fork, int $forks, int $forks_count, string $forks_url, string $full_name, string $git_commits_url, string $git_refs_url, string $git_tags_url, string $git_url, bool $has_downloads, bool $has_issues, bool $has_pages, bool $has_projects, bool $has_wiki, string $homepage, string $hooks_url, string $html_url, int $id, bool $is_template, string $issue_comment_url, string $issue_events_url, string $issues_url, string $keys_url, string $labels_url, string $language, string $languages_url, Schema\WebhookCheckSuiteCompleted\ActionsMeta $license, string $merge_commit_message, string $merge_commit_title, string $merges_url, string $milestones_url, mixed $mirror_url, string $name, string $node_id, string $notifications_url, int $open_issues, int $open_issues_count, Schema\WebhookDeploymentCreated\WorkflowRun\HeadRepository\Owner $owner, bool $private, string $pulls_url, string $pushed_at, string $releases_url, int $size, string $squash_merge_commit_message, string $squash_merge_commit_title, string $ssh_url, int $stargazers_count, string $stargazers_url, string $statuses_url, string $subscribers_url, string $subscription_url, string $svn_url, string $tags_url, string $teams_url, array $topics, string $trees_url, string $updated_at, string $url, bool $use_squash_pr_title_as_default, string $visibility, int $watchers, int $watchers_count, bool $web_commit_signoff_required)
    {
        $this->allow_auto_merge = $allow_auto_merge;
        $this->allow_forking = $allow_forking;
        $this->allow_merge_commit = $allow_merge_commit;
        $this->allow_rebase_merge = $allow_rebase_merge;
        $this->allow_squash_merge = $allow_squash_merge;
        $this->allow_update_branch = $allow_update_branch;
        $this->archive_url = $archive_url;
        $this->archived = $archived;
        $this->assignees_url = $assignees_url;
        $this->blobs_url = $blobs_url;
        $this->branches_url = $branches_url;
        $this->clone_url = $clone_url;
        $this->collaborators_url = $collaborators_url;
        $this->comments_url = $comments_url;
        $this->commits_url = $commits_url;
        $this->compare_url = $compare_url;
        $this->contents_url = $contents_url;
        $this->contributors_url = $contributors_url;
        $this->created_at = $created_at;
        $this->default_branch = $default_branch;
        $this->delete_branch_on_merge = $delete_branch_on_merge;
        $this->deployments_url = $deployments_url;
        $this->description = $description;
        $this->disabled = $disabled;
        $this->downloads_url = $downloads_url;
        $this->events_url = $events_url;
        $this->fork = $fork;
        $this->forks = $forks;
        $this->forks_count = $forks_count;
        $this->forks_url = $forks_url;
        $this->full_name = $full_name;
        $this->git_commits_url = $git_commits_url;
        $this->git_refs_url = $git_refs_url;
        $this->git_tags_url = $git_tags_url;
        $this->git_url = $git_url;
        $this->has_downloads = $has_downloads;
        $this->has_issues = $has_issues;
        $this->has_pages = $has_pages;
        $this->has_projects = $has_projects;
        $this->has_wiki = $has_wiki;
        $this->homepage = $homepage;
        $this->hooks_url = $hooks_url;
        $this->html_url = $html_url;
        $this->id = $id;
        $this->is_template = $is_template;
        $this->issue_comment_url = $issue_comment_url;
        $this->issue_events_url = $issue_events_url;
        $this->issues_url = $issues_url;
        $this->keys_url = $keys_url;
        $this->labels_url = $labels_url;
        $this->language = $language;
        $this->languages_url = $languages_url;
        $this->license = $license;
        $this->merge_commit_message = $merge_commit_message;
        $this->merge_commit_title = $merge_commit_title;
        $this->merges_url = $merges_url;
        $this->milestones_url = $milestones_url;
        $this->mirror_url = $mirror_url;
        $this->name = $name;
        $this->node_id = $node_id;
        $this->notifications_url = $notifications_url;
        $this->open_issues = $open_issues;
        $this->open_issues_count = $open_issues_count;
        $this->owner = $owner;
        $this->private = $private;
        $this->pulls_url = $pulls_url;
        $this->pushed_at = $pushed_at;
        $this->releases_url = $releases_url;
        $this->size = $size;
        $this->squash_merge_commit_message = $squash_merge_commit_message;
        $this->squash_merge_commit_title = $squash_merge_commit_title;
        $this->ssh_url = $ssh_url;
        $this->stargazers_count = $stargazers_count;
        $this->stargazers_url = $stargazers_url;
        $this->statuses_url = $statuses_url;
        $this->subscribers_url = $subscribers_url;
        $this->subscription_url = $subscription_url;
        $this->svn_url = $svn_url;
        $this->tags_url = $tags_url;
        $this->teams_url = $teams_url;
        $this->topics = $topics;
        $this->trees_url = $trees_url;
        $this->updated_at = $updated_at;
        $this->url = $url;
        $this->use_squash_pr_title_as_default = $use_squash_pr_title_as_default;
        $this->visibility = $visibility;
        $this->watchers = $watchers;
        $this->watchers_count = $watchers_count;
        $this->web_commit_signoff_required = $web_commit_signoff_required;
    }
}
