name: "CI: GitHubEnterprise-3.1"
on:
  pull_request:
    paths:
      - ".github/workflows/ci-GitHubEnterprise-3.1.yaml"
      - ".github/workflows/generate-GitHubEnterprise-3.1.yaml"
      - ".github/workflows/release-management-GitHubEnterprise-3.1.yaml"
      - "clients/GitHubEnterprise-3.1/**"
## This workflow needs the `pull-request` permissions to work for the package diffing
## Refs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  pull-requests: write
  contents: read
jobs:
  ci:
    name: Continuous Integration
    uses: WyriHaximus/github-workflows/.github/workflows/package.yaml@main
    with:
      disableMarkdownLinkCheck: true
      disableSetMilestone: true
      workingDirectory: "clients/GitHubEnterprise-3.1"
