name: "Composer Diff"
on:
  pull_request:
    paths:
      - "composer.json"
      - "composer.lock"
## This workflow needs the `pull-request` permissions to work for the package diffing
## Refs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  pull-requests: write
  contents: read
jobs:
  composer-diff:
    name: Composer Diff
    uses: WyriHaximus/github-workflows/.github/workflows/composer-diff.yaml@main
