name: Release Management
on:
  pull_request:
    paths:
      - ".github/workflows/ci-GitHubEnterpriseCloud.yaml"
      - ".github/workflows/generate-GitHubEnterpriseCloud.yaml"
      - ".github/workflows/release-management-GitHubEnterpriseCloud.yaml"
      - "clients/GitHubEnterpriseCloud/**"
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - reopened
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  release-managment:
    name: Release Management
    uses: WyriHaximus/github-workflows/.github/workflows/package-release-managment.yaml@main
